---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: pipelight
    run_list:
      - "recipe[apt]"
      - "recipe[pipelight]"
    attributes:
      apt:
        compile_time_update: true
      pipelight:
        plugins:
          flash:
            accept_license: true
          silverlight5.1:
            accept_license: true
